#############
### build ###
#############

# base image
FROM node:12.2.0 as build

# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /ekalaamu

# add app
COPY . /ekalaamu

# add `/ekalaamu/node_modules/.bin` to $PATH
ENV PATH /ekalaamu/node_modules/.bin:$PATH

# install and cache app dependencies
RUN npm i
RUN npm install -g @angular/cli@7.3.9

# run tests
RUN ng test --watch=false --code-coverage

# generate build
RUN ng build --prod --output-path=dist

############
### prod ###
############
# base image
FROM nginx:1.16.0-alpine

# Part of a Dockerfile
COPY ./nginx.conf /etc/nginx/nginx.conf

# copy artifact build form the build environment
COPY --from=build /ekalaamu/dist /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
